version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    groups:
      python-development:
        patterns: ["ruff", "build", "PyYAML"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
