#!/usr/bin/env python3
"""Build the private-by-default, browser-only PaperTrail playground."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from papertrail_audit import build_audit, render_html
from research_io import atomic_write_json

APP_TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light dark">
  <title>PaperTrail · Audit claims locally</title>
  <style>
    :root{--bg:#f4f4ef;--panel:#fff;--ink:#18211c;--muted:#667168;--line:#d8ddd8;--accent:#155eef;--good:#18794e;--warn:#9a6700;--bad:#c9372c;--purple:#6f42c1;--shadow:0 12px 40px #0000000c}
    @media(prefers-color-scheme:dark){:root{--bg:#101411;--panel:#181e1a;--ink:#eef2ef;--muted:#a9b2ac;--line:#354039;--accent:#79a6ff;--shadow:none}}
    *{box-sizing:border-box}body{margin:0;overflow-x:hidden;background:var(--bg);color:var(--ink);font:15px/1.55 Inter,ui-sans-serif,system-ui,sans-serif}button,input,textarea{font:inherit}a{color:var(--accent)}code{overflow-wrap:anywhere}
    main{width:min(1180px,calc(100% - 32px));margin:auto;padding:46px 0 80px}.language-bar{display:flex;justify-content:flex-end;margin-bottom:16px}.language-control{display:flex;align-items:center;gap:8px;color:var(--muted);font-weight:750}.language-control select{border:1px solid var(--line);border-radius:999px;padding:7px 30px 7px 12px;background:var(--panel);color:var(--ink)}header{display:grid;grid-template-columns:1fr auto;gap:28px;align-items:end;border-bottom:1px solid var(--line);padding-bottom:30px}.eyebrow{color:var(--accent);font-weight:800;letter-spacing:.12em;text-transform:uppercase}h1{font-size:clamp(2.35rem,6vw,5rem);letter-spacing:-.055em;line-height:1;margin:.18em 0}.lede{max-width:760px;color:var(--muted);font-size:1.08rem}.privacy{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:15px 18px;max-width:310px;box-shadow:var(--shadow)}
    h2{font-size:1.5rem;margin:42px 0 14px}.doi-tool{display:flex;gap:9px;align-items:end;margin:0 0 14px}.doi-field{flex:1}.doi-field label{display:block;font-weight:800;margin-bottom:5px}.doi-field input{width:100%;border:1px solid var(--line);border-radius:11px;padding:9px 12px;background:var(--panel);color:var(--ink)}.editor-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:14px}.editor{min-width:0;background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:16px;box-shadow:var(--shadow)}.editor label{display:block;font-weight:800;margin-bottom:8px}.editor-actions{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px}.file-button{color:var(--accent);cursor:pointer;font-weight:700}.file-button input{position:absolute;opacity:0;pointer-events:none}textarea{display:block;width:100%;min-width:0;min-height:290px;resize:vertical;border:1px solid var(--line);border-radius:12px;padding:13px;background:var(--bg);color:var(--ink);font:13px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;tab-size:2}.toolbar{display:flex;gap:9px;flex-wrap:wrap;align-items:center;margin:16px 0}.button{border:1px solid var(--line);border-radius:999px;padding:9px 15px;background:var(--panel);color:var(--ink);cursor:pointer;font-weight:750}.button.primary{background:var(--accent);border-color:var(--accent);color:white}.button:disabled{cursor:not-allowed;opacity:.5}.error{display:none;border-left:4px solid var(--bad);background:var(--panel);padding:12px 15px;border-radius:8px;color:var(--bad);white-space:pre-wrap}.error.visible{display:block}
    .preview-empty{border:1px dashed var(--line);border-radius:18px;padding:36px;text-align:center;color:var(--muted)}.preview-head{display:flex;justify-content:space-between;gap:20px;align-items:start}.preview-head h2{margin:0}.hashes{color:var(--muted);font-size:12px;overflow-wrap:anywhere;white-space:pre-line}.metrics{display:flex;flex-wrap:wrap;gap:9px;margin:18px 0}.metric{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:11px 14px;min-width:135px}.metric strong{display:block;font-size:1.55rem}.claims{display:grid;gap:12px}.claim{background:var(--panel);border:1px solid var(--line);border-radius:17px;padding:18px;box-shadow:var(--shadow)}.claim-top{display:flex;justify-content:space-between;gap:12px}.claim h3{margin:10px 0 4px}.claim-id,.muted{color:var(--muted)}.claim-id{font:700 12px ui-monospace,monospace}.badge,.check{display:inline-block;border-radius:999px;padding:4px 9px;color:#fff;font-size:11px;font-weight:850}.SUPPORTED,.PASS{background:var(--good)}.PARTIALLY_SUPPORTED,.WARN{background:var(--warn)}.CONTRADICTED,.FAIL{background:var(--bad)}.NOT_FOUND{background:var(--purple)}.UNVERIFIABLE,.UNREVIEWED{background:#59636e}
    .evidence{display:grid;gap:8px;margin-top:14px}.evidence-row{display:grid;grid-template-columns:minmax(150px,.8fr) minmax(110px,.45fr) minmax(240px,1.4fr) minmax(130px,.7fr);gap:12px;border-top:1px solid var(--line);padding-top:12px}.field small{display:block;color:var(--muted);font-size:10px;font-weight:850;letter-spacing:.06em;text-transform:uppercase;margin-bottom:4px}.quote{border-left:3px solid var(--accent);padding-left:10px}.graph-wrap{overflow:auto}.graph-wrap svg{display:block;min-width:860px;width:100%}.graph-node{fill:var(--panel);stroke:var(--line)}.graph-text{fill:var(--ink);font:700 12px ui-monospace,monospace}.graph-label{fill:var(--muted);font:12px ui-sans-serif,system-ui,sans-serif}.graph-edge{fill:none;stroke-width:3;opacity:.76}.graph-edge.SUPPORTED{stroke:var(--good)}.graph-edge.PARTIALLY_SUPPORTED{stroke:var(--warn)}.graph-edge.CONTRADICTED{stroke:var(--bad)}.graph-edge.NOT_FOUND{stroke:var(--purple)}.graph-edge.UNVERIFIABLE,.graph-edge.UNREVIEWED{stroke:#59636e}.checklist,.sources{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:9px}.check-card,.source-card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:14px}.check-card{display:flex;gap:10px}.check-card p,.source-card p{margin:3px 0;color:var(--muted)}.source-card h3{font-size:1rem;margin:0 0 5px}.source-meta{font-size:13px}.section-title{display:flex;justify-content:space-between;gap:12px;align-items:center}.integrity-alert{border-left:4px solid var(--bad);background:var(--panel);border-radius:8px;padding:12px 16px;margin:12px 0}
    footer{margin-top:54px;color:var(--muted)}
    @media(max-width:760px){main{width:min(100% - 20px,1180px);padding:28px 0 55px}header{grid-template-columns:1fr;gap:12px}.privacy{max-width:none}.doi-tool{align-items:stretch;flex-direction:column}.editor-grid{grid-template-columns:1fr}textarea{min-height:235px}.preview-head{display:block}.evidence-row{grid-template-columns:1fr 1fr}.field.quote-field{grid-column:1/-1}.metric{flex:1 1 125px}}
    @media(max-width:440px){.section-title{align-items:flex-start;flex-direction:column;gap:3px}.section-title h2{margin-bottom:2px}.evidence-row{grid-template-columns:1fr}.field.quote-field{grid-column:auto}.claim{padding:15px}}
  </style>
</head>
<body><main>
  <div class="language-bar"><label class="language-control" for="language-select"><span data-i18n="language">Language</span><select id="language-select"><option value="en">English</option><option value="zh">简体中文</option></select></label></div>
  <header>
    <div><div class="eyebrow" data-i18n="eyebrow">PaperTrail public playground</div><h1 data-i18n="headline">Audit the trail behind a claim.</h1><p class="lede" data-i18n="lede">Paste or load a Markdown report and its evidence manifest. PaperTrail maps conclusions to exact source excerpts and refuses to turn an unchecked citation into support.</p></div>
    <aside class="privacy"><strong data-i18n="privacy_title">Private by design</strong><br><span class="muted" data-i18n="privacy_body">Reports stay in this browser. DOI lookup contacts Crossref only when you request it; no report text is sent.</span></aside>
  </header>

  <section aria-labelledby="input-title"><div class="section-title"><h2 id="input-title" data-i18n="try_title">Try it locally</h2><a href="demo/" data-i18n="open_demo">Open the published demo report</a></div>
    <div class="doi-tool"><div class="doi-field"><label for="doi-input" data-i18n="doi_label">Optional DOI metadata lookup</label><input id="doi-input" inputmode="url" placeholder="10.1234/example or https://doi.org/…"></div><button class="button" id="doi-button" data-i18n="doi_button">Add source from Crossref</button></div>
    <div class="editor-grid">
      <div class="editor"><div class="editor-actions"><label for="report-input" data-i18n="report_label">Markdown report</label><label class="file-button"><span data-i18n="load_md">Load .md</span><input id="report-file" type="file" accept=".md,text/markdown,text/plain"></label></div><textarea id="report-input" spellcheck="false"></textarea></div>
      <div class="editor"><div class="editor-actions"><label for="manifest-input" data-i18n="manifest_label">Evidence manifest</label><label class="file-button"><span data-i18n="load_json">Load .json</span><input id="manifest-file" type="file" accept=".json,application/json"></label></div><textarea id="manifest-input" spellcheck="false"></textarea></div>
    </div>
    <div class="toolbar"><button class="button primary" id="audit-button" data-i18n="audit_button">Audit locally</button><button class="button" id="draft-button" data-i18n="draft_button">Draft claim candidates</button><button class="button" id="reset-button" data-i18n="reset_button">Restore demo</button><button class="button" id="json-button" data-i18n="download_json" disabled>Download JSON</button><button class="button" id="html-button" data-i18n="download_html" disabled>Download HTML report</button></div>
    <div class="error" id="error" role="alert"></div>
  </section>

  <section aria-labelledby="preview-title"><h2 id="preview-title" data-i18n="preview_title">Audit preview</h2><div id="preview" class="preview-empty" data-i18n="preview_empty">Run the included example or replace it with your own files.</div></section>
  <footer data-i18n="footer">PaperTrail performs a structured evidence audit, not an automatic guarantee of truth. High-stakes verdicts still require independent review.</footer>
</main>
<script type="application/json" id="demo-data">__DEMO_DATA__</script>
<script>
  'use strict';
  const demo=JSON.parse(document.getElementById('demo-data').textContent);
  const reportInput=document.getElementById('report-input'),manifestInput=document.getElementById('manifest-input'),preview=document.getElementById('preview'),errorBox=document.getElementById('error');
  const jsonButton=document.getElementById('json-button'),htmlButton=document.getElementById('html-button'),languageSelect=document.getElementById('language-select');
  const messages={
    en:{page_title:'PaperTrail · Audit claims locally',language:'Language',eyebrow:'PaperTrail public playground',headline:'Audit the trail behind a claim.',lede:'Paste or load a Markdown report and its evidence manifest. PaperTrail maps conclusions to exact source excerpts and refuses to turn an unchecked citation into support.',privacy_title:'Private by design',privacy_body:'Reports stay in this browser. DOI lookup contacts Crossref only when you request it; no report text is sent.',try_title:'Try it locally',open_demo:'Open the published demo report',doi_label:'Optional DOI metadata lookup',doi_button:'Add source from Crossref',report_label:'Markdown report',load_md:'Load .md',manifest_label:'Evidence manifest',load_json:'Load .json',audit_button:'Audit locally',draft_button:'Draft claim candidates',reset_button:'Restore demo',download_json:'Download JSON',download_html:'Download HTML report',preview_title:'Audit preview',preview_empty:'Run the included example or replace it with your own files.',footer:'PaperTrail performs a structured evidence audit, not an automatic guarantee of truth. High-stakes verdicts still require independent review.',audit_eyebrow:'PaperTrail evidence audit',report_hash:'Report',manifest_hash:'Manifest',evidence_graph:'Evidence graph',claims:'Claims',source:'Source',assessment:'Assessment',exact_evidence:'Exact evidence',locator:'Locator',no_citations:'No citations were recorded.',no_quote:'No quote recorded.',not_recorded:'Not recorded',unattributed:'Unattributed',time_unknown:'time unknown',unresolved:'Unresolved',checklist:'Reproducibility checklist',source_registry:'Source registry',unknown:'Unknown',version:'Version',integrity:'Integrity',conflict:'Conflict',yes:'yes',no:'no',integrity_review:'Integrity review required',draft_exists:'This report already contains a claim section. Review it instead of generating a second one.',draft_none:'No strong claim candidates were found. Add a Claims section manually.',draft_added:'Candidate claims were added as drafts. Add citations and human-reviewed evidence before assigning a decisive verdict.',invalid_doi:'Enter a valid DOI.',crossref_failed:'Crossref lookup failed',manifest_shape:'Current manifest must contain sources and evidence arrays.',audit_failed:'No audit was produced. Correct the input error and run it again.',export_footer:'Generated locally by PaperTrail.'},
    zh:{page_title:'PaperTrail · 本地核验结论证据',language:'语言',eyebrow:'PaperTrail 公共试用工具',headline:'追溯每一个结论背后的证据。',lede:'粘贴或载入 Markdown 报告及证据清单。PaperTrail 将结论映射到准确的来源摘录，不会把未经核验的引用当作支持证据。',privacy_title:'隐私优先',privacy_body:'报告始终保留在当前浏览器中。只有主动查询 DOI 时才会联系 Crossref，报告正文不会被发送。',try_title:'在浏览器本地试用',open_demo:'打开已发布的演示报告',doi_label:'可选：查询 DOI 元数据',doi_button:'从 Crossref 添加来源',report_label:'Markdown 报告',load_md:'载入 .md',manifest_label:'证据清单',load_json:'载入 .json',audit_button:'本地核验',draft_button:'生成结论候选草稿',reset_button:'恢复演示内容',download_json:'下载 JSON',download_html:'下载 HTML 报告',preview_title:'核验预览',preview_empty:'运行内置示例，或替换为你自己的文件。',footer:'PaperTrail 提供结构化证据核验，但不会自动保证结论为真。高风险结论仍需独立审阅。',audit_eyebrow:'PaperTrail 证据核验',report_hash:'报告',manifest_hash:'证据清单',evidence_graph:'证据关系图',claims:'结论',source:'来源',assessment:'核验结果',exact_evidence:'准确证据摘录',locator:'位置',no_citations:'尚未记录引用。',no_quote:'尚未记录原文摘录。',not_recorded:'未记录',unattributed:'未署名',time_unknown:'时间未知',unresolved:'未解析来源',checklist:'可复现性清单',source_registry:'来源登记表',unknown:'未知',version:'版本',integrity:'完整性状态',conflict:'冲突',yes:'是',no:'否',integrity_review:'需要完整性复核',draft_exists:'报告已经包含结论章节，请直接审阅，不要重复生成。',draft_none:'未找到明显的结论候选，请手动添加“结论”章节。',draft_added:'已添加候选结论草稿。给出明确判断前，请补充引用、人工核验的原文摘录和位置。',invalid_doi:'请输入有效的 DOI。',crossref_failed:'Crossref 查询失败',manifest_shape:'当前清单必须包含 sources 和 evidence 数组。',audit_failed:'未生成核验结果，请修正输入后重试。',export_footer:'由 PaperTrail 在本地生成。'}
  };
  const verdictLabels={en:{SUPPORTED:'Supported',PARTIALLY_SUPPORTED:'Partially supported',CONTRADICTED:'Contradicted',NOT_FOUND:'Not found',UNVERIFIABLE:'Unverifiable',UNREVIEWED:'Unreviewed'},zh:{SUPPORTED:'支持',PARTIALLY_SUPPORTED:'部分支持',CONTRADICTED:'反驳',NOT_FOUND:'未找到',UNVERIFIABLE:'无法核验',UNREVIEWED:'未审阅'}};
  const checkLabels={en:{PASS:'PASS',WARN:'WARN',FAIL:'FAIL'},zh:{PASS:'通过',WARN:'警告',FAIL:'失败'}};
  const checklistLabels={en:{claims_have_citations:'Claims Have Citations',sources_resolved:'Sources Resolved',reviewed_evidence_has_quotes:'Reviewed Evidence Has Quotes',reviewed_evidence_has_locators:'Reviewed Evidence Has Locators',publication_status:'Publication Status',version_conflicts:'Version Conflicts',review_provenance:'Review Provenance',review_consensus:'Review Consensus',data_availability:'Data Availability',code_availability:'Code Availability'},zh:{claims_have_citations:'结论均有引用',sources_resolved:'来源均已解析',reviewed_evidence_has_quotes:'已审阅证据包含原文',reviewed_evidence_has_locators:'已审阅证据包含位置',publication_status:'发表状态',version_conflicts:'版本冲突',review_provenance:'审阅来源',review_consensus:'审阅一致性',data_availability:'数据开放情况',code_availability:'代码开放情况'}};
  const detailZh={'Every claim has at least one citation.':'每条结论至少包含一个引用。','At least one claim has no citation.':'至少一条结论没有引用。','Every citation resolves in the manifest.':'所有引用都能在证据清单中解析。','Decisive assessments require exact source text.':'明确的核验结论必须包含准确的来源原文。','Decisive assessments require a page, section, paragraph, table, or URL locator.':'明确的核验结论必须包含页码、章节、段落、表格或网址位置。','Publication status is recorded for every resolved source.':'每个已解析来源都记录了发表状态。','At least one source has unknown correction or retraction status.':'至少一个来源的更正或撤稿状态未知。','Every resolved source records no known version conflict.':'所有已解析来源都明确记录无已知版本冲突。','At least one source has not been checked for version conflicts.':'至少一个来源尚未检查版本冲突。','Every reviewed row records reviewer, time, and method.':'每条已审阅证据都记录了审阅者、时间和方式。','Some reviewed evidence lacks reviewer, timestamp, or review method.':'部分已审阅证据缺少审阅者、时间或审阅方式。','No claim/source pair contains both supporting and contradicting reviewer verdicts.':'没有任何结论与来源组合同时出现支持和反驳意见。','Every source declares data availability.':'每个来源都声明了数据开放情况。','Every source declares code availability.':'每个来源都声明了代码开放情况。','No resolved sources were available.':'没有可用的已解析来源。','At least one source declares data unavailable.':'至少一个来源声明数据不可用。','At least one source declares code unavailable.':'至少一个来源声明代码不可用。','At least one source has unknown data availability.':'至少一个来源的数据开放情况未知。','At least one source has unknown code availability.':'至少一个来源的代码开放情况未知。'};
  const verdicts=new Set(Object.keys(verdictLabels.en)),reviewMethods=new Set(['human','ai_assisted','automated','unknown']),claimSections=new Set(['claims','key claims','conclusions','主要结论','核心结论','结论']),highRisk=new Set(['retracted','withdrawn','expression_of_concern']);
  let currentAudit=null,language='en';
  const t=(key)=>messages[language][key]||messages.en[key]||key;
  const verdictText=(value)=>verdictLabels[language][value]||value;
  const checkText=(value)=>checkLabels[language][value]||value;
  function localizeDetail(value){if(language==='en')return value;if(detailZh[value])return detailZh[value];return value.replace(/^Unresolved source IDs: (.+)$/,(_,ids)=>`未解析的来源 ID：${ids}`).replace(/^High-risk publication status: (.+)\.$/,(_,ids)=>`高风险发表状态：${ids}。`).replace(/^Version conflicts require review: (.+)\.$/,(_,ids)=>`需要审阅的版本冲突：${ids}。`).replace(/^Conflicting reviewer verdicts: (.+)\.$/,(_,ids)=>`存在冲突的审阅结论：${ids}。`)}
  const text=(value)=>value==null?'':String(value).trim();
  const node=(tag,className,content)=>{const item=document.createElement(tag);if(className)item.className=className;if(content!==undefined)item.textContent=content;return item};
  const add=(parent,...children)=>{for(const child of children)parent.append(child);return parent};
  const safeUrl=(value)=>{try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)?url.href:''}catch{return''}};
  const citationIds=(value)=>{const found=[];for(const match of value.matchAll(/\[@([^\]]+)\]/g))for(const part of match[1].split(/[;,]/)){const key=part.trim().replace(/^@/,'').trim();if(key&&!found.includes(key))found.push(key)}return found};
  const cleanStatement=(value)=>value.replace(/\[@([^\]]+)\]/g,'').replace(/\s+/g,' ').trim();
  function draftClaims(){setError();if(/^#{1,6}\s+(?:claims|key claims|conclusions|结论|主要结论|核心结论)\s*$/im.test(reportInput.value)){setError(t('draft_exists'));return}const prose=reportInput.value.split(/\r?\n/).filter(line=>!/^\s*(?:#{1,6}\s|```|>)/.test(line)).join(' '),sentences=prose.replace(/\s+/g,' ').split(/(?<=[.!?。！？])\s+/),signals=/(?:\d|%|percent|increase|decrease|associated|significant|demonstrat|suggest|show|find|表明|显示|增加|减少|显著|相关)/i,candidates=sentences.map(text).filter(value=>value.length>=30&&value.length<=500&&signals.test(value)).slice(0,20);if(!candidates.length){setError(t('draft_none'));return}reportInput.value=`${reportInput.value.trim()}\n\n## ${language==='zh'?'结论':'Claims'}\n\n${candidates.map((value,index)=>`- [C${String(index+1).padStart(3,'0')}] ${value}`).join('\n')}\n`;setError(t('draft_added'))}
  const normalizeDoi=(value)=>{const doi=value.trim().replace(/^https?:\/\/(?:dx\.)?doi\.org\//i,'').replace(/^doi:\s*/i,'');if(!/^10\.\d{4,9}\/\S+$/.test(doi))throw new Error(t('invalid_doi'));return doi};
  async function addDoiSource(){setError();const button=document.getElementById('doi-button');button.disabled=true;try{const doi=normalizeDoi(document.getElementById('doi-input').value),response=await fetch(`https://api.crossref.org/works/${encodeURIComponent(doi)}`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`${t('crossref_failed')} (HTTP ${response.status})`);const message=(await response.json()).message||{},updates=Array.isArray(message['update-to'])?message['update-to']:[],types=new Set(updates.map(item=>text(item.type).toLowerCase())),status=types.has('retraction')?'retracted':types.has('withdrawal')?'withdrawn':types.size?'corrected':'active',authors=(message.author||[]).map(author=>`${text(author.given)} ${text(author.family)}`.trim()).filter(Boolean),dates=message['published-print']||message['published-online']||message.issued||{},parts=dates['date-parts']||[],source={id:doi.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),title:(message.title||[])[0]||doi,authors,year:parts[0]?.[0]||null,doi,url:`https://doi.org/${doi}`,publication_status:status,integrity_checked_at:new Date().toISOString().slice(0,10),integrity_url:`https://api.crossref.org/works/${encodeURIComponent(doi)}`,version:'version of record',version_url:message.URL||`https://doi.org/${doi}`,version_conflict:null,version_notes:`Crossref update metadata: ${types.size?[...types].sort().join(', '):'none recorded'}`,data_availability:'unknown',code_availability:'unknown'},manifest=JSON.parse(manifestInput.value);if(!Array.isArray(manifest.sources)||!Array.isArray(manifest.evidence))throw new Error(t('manifest_shape'));const index=manifest.sources.findIndex(item=>item.id===source.id);if(index>=0)manifest.sources[index]=source;else manifest.sources.push(source);manifestInput.value=JSON.stringify(manifest,null,2);document.getElementById('doi-input').value=''}catch(exc){setError(exc instanceof Error?exc.message:String(exc))}finally{button.disabled=false}}
  function parseReport(markdown){
    const lines=markdown.split(/\r?\n/),claims=[];let title='Untitled report',inClaims=false;
    lines.forEach((line,index)=>{const heading=line.match(/^(#{1,6})\s+(.+?)\s*$/);if(heading){const headingText=heading[2].replace(/#+$/,'').trim();if(heading[1].length===1&&title==='Untitled report')title=headingText;inClaims=claimSections.has(headingText.toLowerCase());return}if(!inClaims)return;const listed=line.match(/^\s*(?:[-+*]|\d+[.)])\s+(.+?)\s*$/);if(!listed)return;const explicit=listed[1].match(/^\[(C[A-Za-z0-9_-]+)]\s*(.+)$/i),body=explicit?explicit[2]:listed[1],statement=cleanStatement(body);if(statement)claims.push({id:explicit?explicit[1].toUpperCase():`C${String(claims.length+1).padStart(3,'0')}`,statement,citations:citationIds(body),locator:`report.md#line-${index+1}`})});
    if(!claims.length)throw new Error("No claims found. Add a '## Claims' or '## 结论' list.");
    const ids=claims.map(x=>x.id),duplicate=ids.find((id,index)=>ids.indexOf(id)!==index);if(duplicate)throw new Error(`Duplicate claim ID: ${duplicate}`);return{title,claims};
  }
  function parseManifest(raw){
    let data;try{data=JSON.parse(raw)}catch(exc){throw new Error(`Invalid evidence JSON: ${exc.message}`)}if(!data||typeof data!=='object'||Array.isArray(data))throw new Error('Manifest root must be an object.');
    if(!Array.isArray(data.sources)||!Array.isArray(data.evidence))throw new Error('Manifest sources and evidence must be arrays.');
    const sources=new Map();data.sources.forEach((source,index)=>{if(!source||typeof source!=='object'||Array.isArray(source))throw new Error(`sources[${index}] must be an object.`);const id=text(source.id),title=text(source.title);if(!id||!title)throw new Error(`sources[${index}] requires id and title.`);if(sources.has(id))throw new Error(`Duplicate source ID: ${id}`);if(source.version_conflict!==undefined&&source.version_conflict!==null&&typeof source.version_conflict!=='boolean')throw new Error(`sources[${index}].version_conflict must be true, false, or null.`);sources.set(id,{id,title,authors:Array.isArray(source.authors)?source.authors.map(text).filter(Boolean):text(source.authors)?[text(source.authors)]:[],year:source.year??'',doi:text(source.doi),url:text(source.url),publication_status:text(source.publication_status||'unknown').toLowerCase(),integrity_checked_at:text(source.integrity_checked_at),integrity_url:text(source.integrity_url),version:text(source.version),version_url:text(source.version_url),version_conflict:source.version_conflict??null,version_notes:text(source.version_notes),data_availability:text(source.data_availability||'unknown').toLowerCase(),data_url:text(source.data_url),code_availability:text(source.code_availability||'unknown').toLowerCase(),code_url:text(source.code_url)})});
    const evidence=data.evidence.map((item,index)=>{if(!item||typeof item!=='object'||Array.isArray(item))throw new Error(`evidence[${index}] must be an object.`);const row={claim_id:text(item.claim_id).toUpperCase(),source_id:text(item.source_id),verdict:text(item.verdict||'UNREVIEWED').toUpperCase(),quote:text(item.quote),locator:text(item.locator),note:text(item.note),reviewer_id:text(item.reviewer_id),reviewed_at:text(item.reviewed_at),review_method:text(item.review_method||'unknown').toLowerCase(),review_receipt:text(item.review_receipt)};if(!row.claim_id||!row.source_id)throw new Error(`evidence[${index}] requires claim_id and source_id.`);if(!verdicts.has(row.verdict))throw new Error(`evidence[${index}] has invalid verdict: ${row.verdict}`);if(!reviewMethods.has(row.review_method))throw new Error(`evidence[${index}] has invalid review_method: ${row.review_method}`);if(['SUPPORTED','PARTIALLY_SUPPORTED','CONTRADICTED'].includes(row.verdict)&&(!row.quote||!row.locator))throw new Error(`evidence[${index}] verdict ${row.verdict} requires quote and locator.`);if(row.review_method==='ai_assisted'&&['SUPPORTED','PARTIALLY_SUPPORTED','CONTRADICTED'].includes(row.verdict))throw new Error(`evidence[${index}] AI-assisted draft must remain UNREVIEWED or UNVERIFIABLE.`);return row});return{sources,evidence};
  }
  const aggregate=(citations,rows)=>{if(!citations.length||rows.some(row=>!row.source_resolved))return'UNVERIFIABLE';const values=rows.map(row=>row.verdict);if(!values.length||values.every(x=>x==='UNREVIEWED'))return'UNREVIEWED';if(values.includes('CONTRADICTED'))return'CONTRADICTED';if(values.includes('PARTIALLY_SUPPORTED'))return'PARTIALLY_SUPPORTED';if(values.every(x=>x==='SUPPORTED'))return'SUPPORTED';if(values.every(x=>x==='NOT_FOUND'))return'NOT_FOUND';if(values.includes('UNVERIFIABLE'))return'UNVERIFIABLE';return'PARTIALLY_SUPPORTED'};
  async function digest(value){const bytes=new TextEncoder().encode(value),hash=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
  function availability(sources,kind){if(!sources.length)return{status:'WARN',detail:'No resolved sources were available.'};const states=sources.map(x=>x[`${kind}_availability`]);if(states.every(x=>['available','not_applicable'].includes(x)))return{status:'PASS',detail:`Every source declares ${kind} availability.`};if(states.includes('unavailable'))return{status:'FAIL',detail:`At least one source declares ${kind} unavailable.`};return{status:'WARN',detail:`At least one source has unknown ${kind} availability.`}}
  function renderGraph(audit){const ns='http://www.w3.org/2000/svg',wrap=node('div','graph-wrap'),svg=document.createElementNS(ns,'svg'),height=Math.max(180,Math.max(audit.claims.length,audit.sources.length)*82+36),claimGap=(height-56)/Math.max(1,audit.claims.length),sourceGap=(height-56)/Math.max(1,audit.sources.length),claimY=new Map(audit.claims.map((item,index)=>[item.id,28+index*claimGap])),sourceY=new Map(audit.sources.map((item,index)=>[item.id,28+index*sourceGap]));svg.setAttribute('viewBox',`0 0 960 ${height}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',language==='zh'?'左侧结论与右侧引用来源之间的关系图':'Claims on the left connected to cited sources on the right');for(const claim of audit.claims)for(const sourceId of claim.citations)if(sourceY.has(sourceId)){const path=document.createElementNS(ns,'path'),y1=claimY.get(claim.id)+22,y2=sourceY.get(sourceId)+22;path.setAttribute('d',`M 330 ${y1} C 470 ${y1}, 510 ${y2}, 650 ${y2}`);path.setAttribute('class',`graph-edge ${claim.verdict}`);svg.append(path)}const addNode=(x,y,id,label,width)=>{const group=document.createElementNS(ns,'g'),rect=document.createElementNS(ns,'rect'),idText=document.createElementNS(ns,'text'),labelText=document.createElementNS(ns,'text'),short=label.length<=48?label:`${label.slice(0,47).trim()}…`;group.setAttribute('transform',`translate(${x} ${y})`);rect.setAttribute('width',String(width));rect.setAttribute('height','44');rect.setAttribute('rx','9');rect.setAttribute('class','graph-node');idText.setAttribute('x','12');idText.setAttribute('y','18');idText.setAttribute('class','graph-text');idText.textContent=id;labelText.setAttribute('x','12');labelText.setAttribute('y','35');labelText.setAttribute('class','graph-label');labelText.textContent=short;group.append(rect,idText,labelText);svg.append(group)};for(const claim of audit.claims)addNode(20,claimY.get(claim.id),claim.id,claim.statement,310);for(const source of audit.sources)addNode(650,sourceY.get(source.id),source.id,source.title,290);wrap.append(svg);return wrap}
  async function buildAudit(markdown,manifestRaw){
    const report=parseReport(markdown),manifest=parseManifest(manifestRaw),claimIds=new Set(report.claims.map(x=>x.id));for(const row of manifest.evidence){if(!claimIds.has(row.claim_id))throw new Error(`Evidence references unknown claim: ${row.claim_id}`);if(!manifest.sources.has(row.source_id))throw new Error(`Evidence references unknown source: ${row.source_id}`)}
    const pairs=new Map();for(const row of manifest.evidence){const key=`${row.claim_id}\u0000${row.source_id}`;if(!pairs.has(key))pairs.set(key,[]);pairs.get(key).push(row)}const cited=[],claims=report.claims.map(claim=>{const rows=[];for(const sourceId of claim.citations){if(!cited.includes(sourceId))cited.push(sourceId);const matched=pairs.get(`${claim.id}\u0000${sourceId}`)||[{claim_id:claim.id,source_id:sourceId,verdict:'UNREVIEWED',quote:'',locator:'',note:'No evidence review has been recorded.',reviewer_id:'',reviewed_at:'',review_method:'unknown',review_receipt:''}];for(const item of matched)rows.push({...item,source_resolved:manifest.sources.has(sourceId)})}return{...claim,verdict:aggregate(claim.citations,rows),evidence:rows}});
    const sources=cited.filter(id=>manifest.sources.has(id)).map(id=>manifest.sources.get(id)),unresolved=cited.filter(id=>!manifest.sources.has(id)),reviewed=manifest.evidence.filter(x=>x.verdict!=='UNREVIEWED'),risky=sources.filter(x=>highRisk.has(x.publication_status)),conflicts=sources.filter(x=>x.version_conflict===true),allCited=claims.every(x=>x.citations.length),allKnown=sources.length&&sources.every(x=>x.publication_status!=='unknown'),versionsClear=sources.length&&sources.every(x=>x.version_conflict===false),provenanceComplete=reviewed.length&&reviewed.every(x=>x.reviewer_id&&x.reviewed_at&&x.review_method!=='unknown'),reviewConflicts=[];
    for(const [key,rows] of pairs){const values=new Set(rows.map(x=>x.verdict));if(values.has('CONTRADICTED')&&(['SUPPORTED','PARTIALLY_SUPPORTED'].some(x=>values.has(x))))reviewConflicts.push(key.replace('\u0000','/'))}
    const checklist={claims_have_citations:{status:allCited?'PASS':'FAIL',detail:allCited?'Every claim has at least one citation.':'At least one claim has no citation.'},sources_resolved:{status:unresolved.length?'FAIL':'PASS',detail:unresolved.length?`Unresolved source IDs: ${unresolved.join(', ')}`:'Every citation resolves in the manifest.'},reviewed_evidence_has_quotes:{status:reviewed.length&&reviewed.every(x=>x.quote)?'PASS':'WARN',detail:'Decisive assessments require exact source text.'},reviewed_evidence_has_locators:{status:reviewed.length&&reviewed.every(x=>x.locator)?'PASS':'WARN',detail:'Decisive assessments require a page, section, paragraph, table, or URL locator.'},publication_status:{status:risky.length?'FAIL':allKnown?'PASS':'WARN',detail:risky.length?`High-risk publication status: ${risky.map(x=>x.id).join(', ')}.`:allKnown?'Publication status is recorded for every resolved source.':'At least one source has unknown correction or retraction status.'},version_conflicts:{status:conflicts.length?'FAIL':versionsClear?'PASS':'WARN',detail:conflicts.length?`Version conflicts require review: ${conflicts.map(x=>x.id).join(', ')}.`:versionsClear?'Every resolved source records no known version conflict.':'At least one source has not been checked for version conflicts.'},review_provenance:{status:provenanceComplete?'PASS':'WARN',detail:provenanceComplete?'Every reviewed row records reviewer, time, and method.':'Some reviewed evidence lacks reviewer, timestamp, or review method.'},review_consensus:{status:reviewConflicts.length?'FAIL':'PASS',detail:reviewConflicts.length?`Conflicting reviewer verdicts: ${reviewConflicts.join(', ')}.`:'No claim/source pair contains both supporting and contradicting reviewer verdicts.'},data_availability:availability(sources,'data'),code_availability:availability(sources,'code')};
    const counts={};for(const key of verdicts)counts[key]=claims.filter(x=>x.verdict===key).length;return{schema_version:1,tool:'PaperTrail Web',generated_at:new Date().toISOString(),report:{title:report.title,file:'report.md',sha256:await digest(markdown)},manifest:{file:'evidence.json',sha256:await digest(manifestRaw)},summary:{claims:claims.length,sources:sources.length,unresolved_sources:unresolved.length,verdicts:counts},claims,sources,unresolved_source_ids:unresolved,reproducibility_checklist:checklist,limitations:['A citation match does not by itself establish that a source supports a claim.','Verdicts reflect recorded evidence rows and require independent review for high-stakes use.','Files were processed locally in this browser and were not uploaded by PaperTrail.']};
  }
  function renderAudit(audit){
    preview.className='';preview.removeAttribute('data-i18n');preview.replaceChildren();const head=node('div','preview-head'),titleWrap=node('div');add(titleWrap,node('div','eyebrow',t('audit_eyebrow')),node('h2','',audit.report.title));const hashes=node('div','hashes',`${t('report_hash')} ${audit.report.sha256}\n${t('manifest_hash')} ${audit.manifest.sha256}`);add(head,titleWrap,hashes);preview.append(head);
    const risky=audit.sources.filter(x=>highRisk.has(x.publication_status)||x.version_conflict===true);if(risky.length)preview.append(node('div','integrity-alert',`${t('integrity_review')}：${risky.map(x=>x.id).join(', ')}`));
    const metrics=node('div','metrics');for(const [verdict,count] of Object.entries(audit.summary.verdicts))if(count){const card=node('div','metric');add(card,node('strong','',String(count)),node('span','',verdictText(verdict)));metrics.append(card)}preview.append(metrics,node('h2','',t('evidence_graph')),renderGraph(audit));
    preview.append(node('h2','',t('claims')));const claims=node('div','claims');for(const claim of audit.claims){const card=node('article','claim'),top=node('div','claim-top');add(top,node('span','claim-id',claim.id),node('span',`badge ${claim.verdict}`,verdictText(claim.verdict)));add(card,top,node('h3','',claim.statement),node('div','muted',claim.locator));const rows=node('div','evidence');if(!claim.evidence.length)rows.append(node('p','muted',t('no_citations')));for(const item of claim.evidence){const source=audit.sources.find(x=>x.id===item.source_id),row=node('div','evidence-row'),sourceField=node('div','field');sourceField.append(node('small','',t('source')));const href=source&&safeUrl(source.url);if(href){const link=node('a','',source.title);link.href=href;link.rel='noreferrer';sourceField.append(link)}else sourceField.append(node('div','',source?source.title:`${t('unresolved')}：${item.source_id}`));sourceField.append(node('div','muted',item.source_id));const verdictField=node('div','field');add(verdictField,node('small','',t('assessment')),node('span',`badge ${item.verdict}`,verdictText(item.verdict)));const quoteField=node('div','field quote-field');add(quoteField,node('small','',t('exact_evidence')),node('div',item.quote?'quote':'muted',item.quote||t('no_quote')));const locatorField=node('div','field');add(locatorField,node('small','',t('locator')),node('div','',item.locator||t('not_recorded')),node('p','muted',`${item.reviewer_id||t('unattributed')} · ${item.review_method||t('unknown')} · ${item.reviewed_at||t('time_unknown')}`),node('p','muted',item.note));add(row,sourceField,verdictField,quoteField,locatorField);rows.append(row)}card.append(rows);claims.append(card)}preview.append(claims);
    preview.append(node('h2','',t('checklist')));const checklist=node('div','checklist');for(const [name,item] of Object.entries(audit.reproducibility_checklist)){const card=node('div','check-card');add(card,node('span',`check ${item.status}`,checkText(item.status)));const body=node('div');add(body,node('strong','',checklistLabels[language][name]||name),node('p','',localizeDetail(item.detail)));add(card,body);checklist.append(card)}preview.append(checklist);
    preview.append(node('h2','',t('source_registry')));const sources=node('div','sources');for(const source of audit.sources){const card=node('article','source-card');add(card,node('h3','',source.title),node('div','source-meta',`${source.authors.join(', ')||t('unknown')} · ${source.year||t('unknown')}`),node('p','',`ID: ${source.id} · DOI: ${source.doi||'—'}`),node('p','',`${t('version')}：${source.version||t('unknown')} · ${t('integrity')}：${source.publication_status} · ${t('conflict')}：${source.version_conflict===null?t('unknown'):source.version_conflict?t('yes'):t('no')}`));if(source.version_notes)card.append(node('p','',source.version_notes));sources.append(card)}preview.append(sources);
  }
  function setError(message=''){errorBox.textContent=message;errorBox.classList.toggle('visible',Boolean(message))}
  function applyLanguage(value,{remember=true}={}){language=value==='zh'?'zh':'en';languageSelect.value=language;document.documentElement.lang=language==='zh'?'zh-CN':'en';document.title=t('page_title');for(const item of document.querySelectorAll('[data-i18n]'))item.textContent=t(item.dataset.i18n);if(currentAudit)renderAudit(currentAudit);else{preview.className='preview-empty';preview.setAttribute('data-i18n','preview_empty');preview.textContent=t('preview_empty')}if(remember)try{localStorage.setItem('papertrail-language',language)}catch{}}
  function restore(){reportInput.value=demo.report;manifestInput.value=demo.manifest;currentAudit=null;jsonButton.disabled=true;htmlButton.disabled=true;preview.className='preview-empty';preview.setAttribute('data-i18n','preview_empty');preview.textContent=t('preview_empty');setError()}
  async function run(){setError();try{currentAudit=await buildAudit(reportInput.value,manifestInput.value);renderAudit(currentAudit);jsonButton.disabled=false;htmlButton.disabled=false;preview.scrollIntoView({behavior:'smooth',block:'start'})}catch(exc){currentAudit=null;jsonButton.disabled=true;htmlButton.disabled=true;preview.className='preview-empty';preview.setAttribute('data-i18n','preview_empty');preview.textContent=t('audit_failed');setError(exc instanceof Error?exc.message:String(exc))}}
  function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  document.getElementById('audit-button').addEventListener('click',run);document.getElementById('draft-button').addEventListener('click',draftClaims);document.getElementById('reset-button').addEventListener('click',restore);document.getElementById('doi-button').addEventListener('click',addDoiSource);languageSelect.addEventListener('change',()=>applyLanguage(languageSelect.value));jsonButton.addEventListener('click',()=>currentAudit&&download('audit.json',JSON.stringify(currentAudit,null,2)+'\n','application/json'));htmlButton.addEventListener('click',()=>{if(!currentAudit)return;const title=currentAudit.report.title.replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])),css=document.querySelector('style').textContent,body=preview.outerHTML;download('papertrail-report.html',`<!doctype html><html lang="${document.documentElement.lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · PaperTrail</title><style>${css}</style></head><body><main>${body}<footer>${t('export_footer')}</footer></main></body></html>`,'text/html')});
  for(const [fileId,input] of [['report-file',reportInput],['manifest-file',manifestInput]])document.getElementById(fileId).addEventListener('change',async event=>{const file=event.target.files[0];if(file)input.value=await file.text()});let preferred='';try{preferred=localStorage.getItem('papertrail-language')||''}catch{}applyLanguage(preferred||((navigator.language||'').toLowerCase().startsWith('zh')?'zh':'en'),{remember:false});restore();
</script></body></html>"""


def render_app_html(demo_report: str, demo_manifest: str) -> str:
    payload = json.dumps(
        {"report": demo_report, "manifest": demo_manifest},
        ensure_ascii=False,
        separators=(",", ":"),
    ).replace("</", "<\\/")
    return APP_TEMPLATE.replace("__DEMO_DATA__", payload)


def build_site(output_dir: Path, demo_report: Path, demo_manifest: Path) -> None:
    report_text = demo_report.read_text(encoding="utf-8")
    manifest_text = demo_manifest.read_text(encoding="utf-8")
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "index.html").write_text(render_app_html(report_text, manifest_text), encoding="utf-8", newline="\n")
    (output_dir / ".nojekyll").write_text("", encoding="utf-8")

    demo_dir = output_dir / "demo"
    demo_dir.mkdir(exist_ok=True)
    audit = build_audit(demo_report.resolve(), demo_manifest.resolve())
    atomic_write_json(demo_dir / "audit.json", audit)
    (demo_dir / "index.html").write_text(render_html(audit), encoding="utf-8", newline="\n")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("papertrail-site"))
    parser.add_argument("--demo-report", required=True, type=Path)
    parser.add_argument("--demo-manifest", required=True, type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        build_site(args.output_dir, args.demo_report, args.demo_manifest)
    except (OSError, ValueError) as exc:
        print(f"ERROR: {exc}")
        return 2
    print(f"site={args.output_dir / 'index.html'}")
    print(f"demo={args.output_dir / 'demo' / 'index.html'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
